### ISSUE TITLE
[Feature Request]create gh-page for documentation

### ISSUE THREAD

**Issue by Freymaurer** [Freymaurer/PathfinderAttackSimulator#3]
**Is your feature request related to a problem? Please describe.**
Functions might be unclear to use, especially the library currently.

**Describe the solution you'd like**
have a gh-page -based documentary as tutorial-like structure

**Comment by caroott** [comment]
Created branch gh-pages for documentation. Actual documentation still needs to be added.

**Comment by Freymaurer** [comment]
So what we need to do now is the following

- [x] establish a page structure similiar to BioFSharp, preferably with f# formatting and not markdown
- [ ] create the docs
- [ ] change README.md to link to docs
